Add keepMounted and itemProps to Vue API to enable sticky groups
inokawa/virtua pull request #576
Opened 2024-12-09 06:37 UTC by AmitJoki

I wanted to use virtua for the usecase of sticky groups + virtualized scrolls in Vue but found that the APIs for that is not yet there.

I have added `keepMounted` from the React API and an additional `itemProps` to facilitate the Sticky Groups in Vue.

I have also added a story for the same.

If the PR is okay in its direction, I can add some documentation as well if needed.

2024-12-09 07:02 UTC, inokawa requested changes
Hi, thanks for the PR.

The docs will be autogenerated from JSDoc so you don't need to modify /docs dir.

2024-12-09 07:02 UTC, inokawa commented on src/vue/VList.tsx
> +  itemProps: Function as PropType<ItemProps>,
Could you try existed `item` prop instead of adding new prop? I don't think we need 2 props for 1 purpose.

```suggestion
```

2024-12-09 09:18 UTC, AmitJoki commented on src/vue/VList.tsx
> +  itemProps: Function as PropType<ItemProps>,
Refs work a bit differently in Vue https://vuejs.org/guide/essentials/template-refs and there's no equivalent of `forwardRef`

Also, on native elements, the ref correctly points to the DOM element but for a Vue component, the structure changes and the ref points to the component's *instance* and you have to use `.$el` to actually get the DOM element.

Also while JSX is "supported", SFCs are the first-class way of building Vue applications and there refs are extracted from the template. 

The `item` prop only accepts the native element and not user component like it does in React API perhaps for the reasons laid out above.

2024-12-09 09:40 UTC, inokawa commented on src/vue/VList.tsx
> +  itemProps: Function as PropType<ItemProps>,
Thanks for the replay.

> Also while JSX is "supported", SFCs are the first-class way of building Vue applications and there refs are extracted from the template.

Okay, we have a plan to migrate to SFC (#556). So we need to complete it at first, and change `item` prop to accept `element` and `component`. You mean it's possible with SFC, right?

2024-12-10 02:48 UTC, AmitJoki commented on src/vue/VList.tsx
> +  itemProps: Function as PropType<ItemProps>,
@inokawa yes it is possible. Here's how one could do it using ref function:  [Playground](https://play.vuejs.org/#eNp9U2Fv0zAQ/SsnC6mtNDmaCl9ChwSoEkMwpjH4ghGKkkvn4diR7aRFVf87Z6dNk3bblza+93z3fO9uy97XNW8bZClbuNzK2oND39TvhJZVbayHn9L6Jrv2WEFpTQUTnhxD4erkbc/94dB+NPStUfuePooebiySrhwVogOlqlXmkU4Ai0FJST9XghWyFQySMzjd46MSe+YiGWRlF8y73OhSrvijM5reuw3JBMvpmlRov9VeGu0ESyEiAcuUMuvPMeZtgxeHeP6A+d8n4o9uE2KC3VokRS0K1mM+syskbQFefr/BDX33YGWKRhH7BfAOnVFN0NjRPjS6INkDXlR7HZ2QenXvlhuP2h0eFYQG5i7yBSMfQseee/pR7py/jveE3lEXx96HsRl7F9rZ2Z9KR84Eg8iQ1GJJJ5qtOywF67hJTz61Kw7FcB7B/6uREnhSeZzNLVBa2O0nbT9ZQhdYSo231tRu+msSFEx+zyJCE+A8oMKKipISuAoZph1YNjoPjQgVCZvirGuHLGGKIOlmpnM0JXy6//pl2eWYDZLxNlMNUkqkdECAwydR/gpVLAiwlrowa56RCX56yuU+W91kFQZ11P3RxpATZ2t1tsMv7djDZfynL6eMP6xWEsOnm/OnRRvmiArM+Rt+OWe7/xoOcIY=)

`VirtualItem` component accepts `item` prop which can be a string for native elements or the component itself. The `setRef` function will distinguish between the two and give you the correct DOM element be it a native element or a user component.

2024-12-14 11:58 UTC, inokawa commented on src/vue/VList.tsx
> +  itemProps: Function as PropType<ItemProps>,
@AmitJoki 
Thank you. It's very helpful!

And I'm sorry for my late reply. Migrating to SFC may take a lot of time so I'll merge this PR anyway. And I may deprecate `itemProps` and merge it into `item` in near future.

2024-12-14 11:58 UTC, inokawa approved these changes

2024-12-14 12:14 UTC, merged

2024-12-14 12:35 UTC, inokawa commented
Released in `0.39.1`.